name: Check

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libtorrent-rasterbar-dev libglib2.0-dev libgit2-dev libcurl4-openssl-dev valgrind gcovr clang-tidy
          version: 1.0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: cpplint-cache

      - name: Install cpplint
        run: pip install cpplint

      - name: Lint Check
        run: |
          make lint
